.github/pull_request_template.md

- https://cultivate-software.atlassian.net/browse/TIO-26

docs: introduce PR template

---

.github/dependabot.yaml
.github/pull_request_template.md

- https://cultivate-software.atlassian.net/browse/TIO-26

ci: undo accidental changes to PR template

---

.github/dependabot.yaml
.github/workflows/pr--verify.yaml
README.md
docs/dependabot.md
docs/enable-dependabot-auto-merge.md

- https://cultivate-software.atlassian.net/browse/TIO-16

fix: TIO-16: Setup Dependabot

---

.github/workflows/pr--verify.yaml
.github/workflows/reusable-verify.yaml
pubspec.lock
pubspec.yaml
scripts/app.sh

- https://cultivate-software.atlassian.net/browse/TIO-21

ci: TIO-21: validate total test coverage against given threshold

---

.github/workflows/bump-build-number.yaml

ci: use branch to bump version

---

.github/workflows/pipeline.yaml

ci: TIO-27: run pipeline when bumping build number finished

---

.github/workflows/pipeline.yaml

ci: TIO-27: use valid artifact name without slashes

---

.github/workflows/reusable-upload-ios-app.yaml
ios/fastlane/Fastfile
scripts/load-version-and-build-number-from-latest-tag.sh

ci: TIO-27: use correct ios build file name; fix loading latest tag

---

.github/workflows/reusable-build-android-app.yaml
.github/workflows/reusable-build-ios-app.yaml
.github/workflows/reusable-upload-android-app.yaml
.github/workflows/reusable-upload-ios-app.yaml
scripts/load-version-and-build-number-from-latest-tag.sh

ci: TIO-27: fail early when no git tag can be found; fetch with history

---

.github/workflows/pr--verify.yaml

- https://cultivate-software.atlassian.net/browse/TIO-16

fix: TIO-16: use GitHub token with permissions

---

.github/workflows/pr--verify.yaml

fix: TIO-16: set up alternative auto-merge action

---

.github/workflows/pr--verify.yaml

fix: TIO-16: set up alternative auto merge configuration

---

.github/dependabot.yaml
pubspec.lock
pubspec.yaml

fix: TIO-16: downgrade patch version to test auto-merge

---

pubspec.lock
pubspec.yaml

build: TIO-16: reinstall downgraded version

---

docs/dependabot.md

docs: TIO-16: update Dependabot documentation

---

.github/workflows/reusable-build-android-app.yaml
pubspec.yaml

- https://cultivate-software.atlassian.net/browse/TIO-28

ci: TIO-28: ensure correct NDK is used

---

ios/Runner/Runner.entitlements

- https://cultivate-software.atlassian.net/browse/TIO-94

fix: TIO-94: add push notifications entitlement

---

lib/main.dart
lib/models/blocks/image_block.dart
lib/models/file_io.dart
lib/pages/image/image_page.dart

- https://cultivate-software.atlassian.net/browse/TIO-96

fix: TIO-96: Fix add image to project issues

---

.gitignore
analysis_options.yaml
lib/main.dart
lib/models/blocks/empty_block.dart
lib/models/blocks/image_block.dart
lib/models/blocks/media_player_block.dart
lib/models/blocks/metronome_block.dart
lib/models/blocks/piano_block.dart
lib/models/blocks/text_block.dart
lib/models/blocks/tuner_block.dart
lib/models/project_block.dart
lib/models/rhythm_group.dart
lib/pages/info_pages/about_page.dart
lib/pages/media_player/media_player.dart
lib/pages/media_player/setting_bpm.dart
lib/pages/media_player/setting_speed.dart
lib/pages/parent_tool/parent_tool.dart
lib/pages/project_page/export_project_dialog.dart
lib/pages/project_page/project_page.dart
lib/pages/projects_list/import_project_dialog.dart
lib/pages/projects_list/projects_list.dart
lib/util/walkthrough_util.dart
lib/widgets/input/app_slider_int.dart
lib/widgets/tap_to_tempo.dart
pubspec.lock
pubspec.yaml
scripts/app.sh
test/widgets/input/number_input_double_with_slider_test.dart
test/widgets/input/number_input_int_with_slider_test.dart

- https://cultivate-software.atlassian.net/browse/TIO-81

refactor: TIO-81: setup linting rules and fix most issues

---

lib/pages/project_page/export_project_dialog.dart
lib/pages/projects_list/import_project_dialog.dart

- https://cultivate-software.atlassian.net/browse/TIO-74

fix: TIO-74: export media player files

---

lib/pages/tuner/play_sound_page.dart

- https://cultivate-software.atlassian.net/browse/TIO-99

fix: TIO-99: show frequency in tuner

---

README.md
docs/upgrade-ios-android-sdks.md
ios/Flutter/AppFrameworkInfo.plist
ios/Podfile.lock
pubspec.lock
rust/Cargo.lock

- https://cultivate-software.atlassian.net/browse/TIO-127

fix: TIO-127: upgrade iOS SDK

---

.github/workflows/reusable-build-ios-app.yaml
docs/upgrade-ios-android-sdks.md

- https://cultivate-software.atlassian.net/browse/TIO-127

fix: TIO-127: refactor pipeline steps

---

.github/workflows/reusable-build-ios-app.yaml
docs/upgrade-ios-android-sdks.md

- https://cultivate-software.atlassian.net/browse/TIO-127

fix: TIO-127: Restore step for Xcode installation to fix pipeline

---

.github/workflows/pr--label-dependabot-pull-requests.yaml
scripts/label-pr-by-semver.sh

- https://cultivate-software.atlassian.net/browse/TIO-131

fix: TIO-131: fix variable name in script

---

.github/workflows/pr--label-dependabot-pull-requests.yaml
docs/dependabot.md
scripts/label-pr-by-semver.sh

- https://cultivate-software.atlassian.net/browse/TIO-131

fix: TIO-131: Fix pipeline issues

---

.github/workflows/reusable-build-ios-app.yaml

- https://cultivate-software.atlassian.net/browse/TIO-127

build: TIO-127: use iOS SDK 18

---

.github/workflows/reusable-build-ios-app.yaml
docs/dependabot.md
lib/models/blocks/piano_block.dart
lib/models/blocks/piano_block.g.dart
lib/pages/piano/piano.dart
lib/pages/piano/set_concert_pitch.dart
lib/pages/project_page/export_project_dialog.dart
lib/src/rust/api/api.dart
lib/src/rust/frb_generated.dart
pubspec.lock
rust/Cargo.lock
rust/src/api/api.rs
rust/src/api/modules/piano.rs
rust/src/frb_generated.rs
scripts/app.sh

- https://cultivate-software.atlassian.net/browse/TIO-78
Piggyback two changes from ticket TIO-131:
- update docs
- use more specific version and name for installing Xcode

fix: TIO-78: manually change concert pitch in piano

---

.github/workflows/pipeline.yaml
.github/workflows/reusable-upload-android-app.yaml
.github/workflows/reusable-upload-ios-app.yaml

- https://cultivate-software.atlassian.net/browse/TIO-36

ci: TIO-36: report deployments to GitHub

---

analysis_options.yaml
lib/models/blocks/image_block.dart
lib/models/file_io.dart
lib/pages/media_player/media_player_functions.dart

- https://cultivate-software.atlassian.net/browse/TIO-81

refactor: TIO-81: enable linting rule avoid slow async and fix issues

---

.github/workflows/pipeline.yaml

- https://cultivate-software.atlassian.net/browse/TIO-36

ci: TIO-36: fix workflow permissions

---

.github/workflows/pipeline.yaml

- https://cultivate-software.atlassian.net/browse/TIO-36

ci: TIO-36: fix permissions

---

.github/workflows/pr--verify.yaml

- https://cultivate-software.atlassian.net/browse/TIO-131

ci: TIO-131: add logging to understand why Dependabot does not auto-merge

---

.github/workflows/reusable-upload-ios-app.yaml

- https://cultivate-software.atlassian.net/browse/TIO-36

ci: TIO-36: fix action version number

---

.github/workflows/pr--verify.yaml

- https://cultivate-software.atlassian.net/browse/TIO-131

ci: TIO-131: improve debug output

---

lib/pages/tuner/play_sound_page.dart

- https://cultivate-software.atlassian.net/browse/TIO-138

fix: TIO-138: fix offset for tuner play reference calculation

---

lib/pages/metronome/metronome.dart
lib/pages/metronome/metronome_island_view.dart
lib/pages/metronome/setting_rhythm_parameters.dart
lib/util/constants.dart
test/widgets/metronome/metronome_functions_test.dart

- https://cultivate-software.atlassian.net/browse/TIO-75

fix: TIO-75: refactor and test metronome flash on and off functionality

---

lib/pages/piano/piano.dart

- https://cultivate-software.atlassian.net/browse/TIO-78

fix: TIO-78(piano): show instrument and herz

---

lib/pages/piano/piano.dart

- https://cultivate-software.atlassian.net/browse/TIO-78

style: TIO-78(piano): change styling of herz and instrument

---

ios/fastlane/Fastfile

- https://cultivate-software.atlassian.net/browse/TIO-143

ci: TIO-143: auto-release new iOS builds to external testers

---

.github/workflows/bump-build-number.yaml
.github/workflows/pr--verify-title.yaml
.github/workflows/release.yaml
.github/workflows/reusable-build-android-app.yaml
.github/workflows/reusable-build-ios-app.yaml
.github/workflows/reusable-upload-android-app.yaml
.github/workflows/reusable-upload-ios-app.yaml
.releaserc.yml

ci: TIO-148: add workflow to simplify app releases

---

ios/fastlane/Fastfile

- https://cultivate-software.atlassian.net/browse/TIO-143

ci: TIO-143: add external testing group

---

.github/workflows/pr--verify-title.yaml

- https://cultivate-software.atlassian.net/browse/TIO-149

ci: TIO-149: verify that PR title contains JIRA ticket number

---

.github/workflows/pr--verify-title.yaml

ci: TIO-149: improve error message when checking PR title

---

.github/workflows/bump-build-number.yaml
.github/workflows/release.yaml
scripts/bump-build-number-and-tag.sh
scripts/load-version-and-build-number-from-latest-tag.sh

- https://cultivate-software.atlassian.net/browse/TIO-143

ci: TIO-143: mark build tags with 'b' and release tags with 'r'

---

.releaserc.yml

ci: TIO-148: fix semantic release config

---

.github/workflows/pipeline.yaml

ci: TIO-148: trigger pipeline on release

---

scripts/bump-build-number-and-tag.sh

ci: TIO-148: fix bug in bump build number script

---

.github/workflows/pipeline.yaml

ci: TIO-148: skip jobs when bumping build number failed

---

.github/workflows/bump-build-number.yaml

ci: TIO-148: bump build number on release

---

.github/workflows/bump-build-number.yaml

ci: TIO-148: remove trigger by tag

---

.github/pull_request_template.md

- https://cultivate-software.atlassian.net/browse/TIO-26

ci: TIO-26: simplify PR template after moving JIRA number to title

---

.github/workflows/pr--verify.yaml

ci: TIO-141: source script to load bump type

---

scripts/app.sh
scripts/build.sh
scripts/run.sh
scripts/upload.sh

ci: TIO-150: refactor app script into sub scripts

---

lib/l10n/app_localization.dart
lib/l10n/de.dart
lib/l10n/en.dart
lib/pages/media_player/edit_markers_page.dart
lib/pages/media_player/media_player.dart
lib/pages/media_player/media_player_functions.dart
lib/pages/media_player/setting_bpm.dart
lib/pages/media_player/setting_pitch.dart
lib/pages/media_player/setting_speed.dart
lib/pages/media_player/setting_trim.dart
lib/util/constants.dart
lib/util/util_functions.dart
lib/widgets/tap_to_tempo.dart

feat(l10n): TIO-156: localization media player

---

lib/l10n/app_localization.dart
lib/l10n/de.dart
lib/l10n/en.dart
lib/pages/media_player/media_player.dart
lib/pages/metronome/metronome.dart
lib/pages/metronome/metronome_island_view.dart
lib/pages/metronome/setting_bpm.dart
lib/pages/metronome/setting_metronome_sound.dart
lib/pages/metronome/setting_random_mute.dart
lib/pages/metronome/setting_rhythm_parameters.dart

feat(l10n): TIO-153: localization metronome

---

lib/l10n/app_localization.dart
lib/l10n/de.dart
lib/l10n/en.dart
lib/pages/parent_tool/parent_island_view.dart

feat(l10n): TIO-161: localize parent island view

---

lib/l10n/app_localization.dart
lib/l10n/de.dart
lib/l10n/en.dart
lib/main.dart
lib/pages/parent_tool/parent_island_view.dart

feat(l10n): TIO-161: localization main

---

lib/models/blocks/image_block.dart
lib/models/blocks/media_player_block.dart
lib/models/blocks/metronome_block.dart
lib/models/blocks/piano_block.dart
lib/models/blocks/text_block.dart
lib/models/blocks/tuner_block.dart
lib/pages/piano/piano.dart
lib/util/constants.dart

refactor: TIO-161: delete old tool block infos

---

lib/l10n/app_localization.dart
lib/l10n/de.dart
lib/l10n/en.dart
lib/models/blocks/image_block.dart
lib/models/blocks/media_player_block.dart
lib/models/blocks/metronome_block.dart
lib/models/blocks/piano_block.dart
lib/models/blocks/text_block.dart
lib/models/blocks/tuner_block.dart
lib/models/project_block.dart
lib/pages/parent_tool/parent_island_view.dart
lib/pages/parent_tool/parent_tool.dart
lib/pages/piano/choose_sound.dart
lib/pages/piano/piano.dart
lib/pages/project_page/project_page.dart
lib/util/constants.dart

feat(l10n): TIO-161: localize piano sound fonts

---

lib/pages/media_player/media_player.dart

fix: TIO-161: fix translations

---

lib/l10n/app_localization.dart
lib/l10n/de.dart
lib/l10n/en.dart
lib/pages/metronome/metronome.dart
lib/pages/parent_tool/setting_volume_page.dart
lib/pages/parent_tool/volume.dart

feat(l10n): TIO-161: localize shared volume page

---

lib/l10n/app_localization.dart
lib/l10n/de.dart
lib/l10n/en.dart
lib/pages/info_pages/feedback_page.dart

The survey hint that the survey is only available in German is deleted.

refactor: TIO-161: update localizations

---

lib/l10n/app_localization.dart
lib/l10n/de.dart
lib/l10n/en.dart
lib/pages/media_player/edit_markers_page.dart
lib/pages/media_player/media_player.dart
lib/pages/media_player/media_player_functions.dart
lib/pages/media_player/setting_trim.dart
lib/pages/parent_tool/parent_island_view.dart
lib/pages/parent_tool/parent_tool.dart
lib/pages/piano/piano.dart
lib/pages/projects_list/projects_list.dart
lib/util/util_functions.dart

feat(l10n): TIO-167: localize date format

---

lib/l10n/app_localization.dart
lib/l10n/de.dart
lib/l10n/en.dart
lib/pages/text/import_text.dart
lib/pages/text/text.dart

feat(import): TIO-102: file import in text widget

---

.github/workflows/pr--verify-title.yaml
.github/workflows/reusable-build-android-app.yaml
.github/workflows/reusable-build-ios-app.yaml

The PR title is now checked for an issue number.
Also checks and fails pipeline if app bundle was uploaded after build.

ci: TIO-173: require issue number in PR title

---

lib/l10n/de.dart

fix: TIO-161: change translations

---

.github/workflows/pipeline.yaml
.github/workflows/pr--verify.yaml
.github/workflows/release.yaml
.github/workflows/reusable-bump-build-number.yaml
scripts/bump-build-number-and-tag.sh
scripts/load-build-number-from-latest-tag.sh
scripts/load-version-from-latest-tag.sh

- uses auto-merge feature as intended
- adds auto-approval
- bumps build number on pipeline run instead of pipeline on build-number run (this eliminates an issue with building with the same build number twice after triggering a release)

ci: TIO-141: fix dependabot auto-merging

---

.github/workflows/release.yaml

ci: TIO-141: revert removing permissions

---

.github/workflows/pr--verify.yaml

ci: TIO-141: disable auto-approval until it's enabled on org level

---

.github/workflows/pipeline.yaml
.github/workflows/release.yaml
.github/workflows/reusable-bump-build-number.yaml

fix: TIO-86: fix output names

---

.github/workflows/pipeline.yaml

ci: TIO-86: fix job dependencies to access ouptputs

---

.github/workflows/release.yaml
.github/workflows/reusable-bump-build-number.yaml
lib/services/decorators/file_system_log_decorator.dart
scripts/bump-build-number-and-tag.sh
scripts/bump-dev-version-and-tag.sh
scripts/load-build-number-from-latest-tag.sh
scripts/load-release-version-from-latest-tag.sh

ci: TIO-86: prepare dev version after release

---

.github/workflows/reusable-build-android-app.yaml
.github/workflows/reusable-build-ios-app.yaml
.github/workflows/reusable-bump-build-number.yaml
.github/workflows/reusable-upload-android-app.yaml
.github/workflows/reusable-upload-ios-app.yaml
.github/workflows/reusable-verify.yaml

fix: TIO-86: improve workflow input descriptions

---

.github/workflows/pipeline.yaml
.github/workflows/reusable-build-android-app.yaml
.github/workflows/reusable-build-ios-app.yaml
.github/workflows/reusable-bump-build-number.yaml
.github/workflows/reusable-upload-android-app.yaml
.github/workflows/reusable-upload-ios-app.yaml
.releaserc.yml
scripts/set-version-in-pubspec.sh

fix: TIO-86: combine semver and build number in workflows

---

.releaserc.yml

fix: TIO-86: ignore pre-release tags

---

scripts/load-version-from-latest-tag.sh

fix: TIO-86: loading of version from latest tag

---

lib/pages/piano/piano.dart

fix: TIO-176: fix default project thumbnail for saving piano quick tool

---

lib/pages/project_page/edit_project_bar.dart
lib/pages/project_page/project_page.dart

fix: TIO-120: show additional button for editing on bottom

---

lib/pages/tuner/play_sound_page.dart

fix: TIO-174: localize tuner frequency

---

lib/pages/project_page/project_page.dart

fix: TIO-120: fix visual background issue

---

.github/workflows/reusable-verify.yaml
analysis_options.yaml
lib/models/blocks/image_block.dart
scripts/app.sh

refactor: TIO-81: enable linting rule sort_unnamed_constructors_first

---

analysis_options.yaml
lib/util/util_functions.dart
scripts/app.sh

refactor: TIO-81: enable linting rule use_string_buffers

---

analysis_options.yaml
lib/models/blocks/empty_block.dart
lib/models/blocks/image_block.dart
lib/models/blocks/media_player_block.dart
lib/models/blocks/metronome_block.dart
lib/models/blocks/piano_block.dart
lib/models/blocks/text_block.dart
lib/models/blocks/tuner_block.dart
lib/models/icon_converter.dart
lib/models/project_block.dart
lib/pages/info_pages/about_page.dart
lib/pages/media_player/media_player.dart
lib/util/app_snackbar.dart
lib/util/directional_page_route.dart
lib/util/log.dart
lib/widgets/tool_navigation_bar.dart
test/mocks/file_picker_mock.dart

refactor: TIO-81: enable linting rule always_declare_return_types

---

lib/pages/metronome/rhythm/setting_rhythm_parameters.dart
lib/util/directional_page_route.dart
lib/util/util_functions.dart

fix: TIO-97: fix metronome beat colors

---

.github/workflows/reusable-verify.yaml
lib/pages/metronome/rhythm/setting_rhythm_parameters.dart

- use different icon to represent advanced mode
- reset poly beats when switching to simple mode
- lint yaml files after checking for changed files

fix: TIO-97: minor metronome rhythm settings improvements

---

lib/l10n/de.dart
lib/l10n/en.dart
test/widgets/input/number_input_and_slider_dec_test.dart
test/widgets/input/number_input_and_slider_int_test.dart

refactor: TIO-188: update l10n

---

.github/workflows/reusable-verify.yaml
lib/l10n/app_localization.dart
lib/l10n/de.dart
lib/l10n/en.dart
lib/models/project.dart
lib/models/project.g.dart
lib/models/project_block.dart
lib/models/project_block.g.dart
lib/pages/image/image_page.dart
lib/pages/project_page/edit_project_bar.dart
lib/pages/project_page/editable_tool_list.dart
lib/pages/project_page/project_page.dart
lib/pages/project_page/tool_list.dart
lib/pages/projects_page/edit_projects_bar.dart
lib/pages/projects_page/editable_project_list.dart
lib/pages/projects_page/import_project.dart
lib/pages/projects_page/project_list.dart
lib/pages/projects_page/projects_page.dart
lib/util/util_functions.dart
lib/widgets/small_icon_button.dart
test/integration/projects/projects_test.dart

fix: TIO-177: fix bug when importing project with same id

---

.github/workflows/release.yaml

ci: TIO-000: improve tagging and releasing

---

.github/workflows/reusable-verify.yaml
lib/pages/piano/piano.dart
lib/widgets/input/edit_text_dialog.dart
lib/widgets/input/flat_edit_text_dialog.dart
test/widgets/input/flat_edit_text_dialog_test.dart

fix: TIO-145: provide horizontal edit title dialog in piano

---

lib/pages/projects_page/projects_page.dart

fix: TIO-182: show welcome tutorial page as first page

---

lib/l10n/de.dart
lib/l10n/en.dart
lib/pages/media_player/media_player.dart

fix: TIO-220: change order of tool settings

---

.github/workflows/reusable-verify.yaml
lib/pages/image/image_page.dart

fix: TIO-217: reset thumbnail when previously used as thumbnail

---

lib/pages/metronome/advanced_rhythm_group_editor.dart
lib/pages/metronome/metronome.dart
lib/pages/metronome/metronome_functions.dart
lib/pages/metronome/metronome_island_view.dart
lib/pages/metronome/metronome_utils.dart
lib/pages/metronome/setting_bpm.dart
lib/pages/metronome/setting_metronome_sound.dart
lib/pages/metronome/setting_random_mute.dart

refactor: TIO-152: inject AudioSystem into Metronome

---

ios/fastlane/Fastfile
scripts/load-semver-from-latest-tag.sh

chore: TIO-000: use correct script to load semantic version

---

flutter_native_splash.yaml

chore: TIO-000: enable flavors for flutter_native_splash

---

ios/Runner.xcodeproj/xcshareddata/xcschemes/dev.xcscheme
ios/Runner.xcodeproj/xcshareddata/xcschemes/prd.xcscheme

chore: TIO-000: share new schemes with all developers

---

android/app/build.gradle
android/app/src/main/kotlin/com/example/flutter_rust_bridge_template/MainActivity.kt
android/fastlane/Appfile

chore: TIO-000: use valid package name

---

lib/l10n/de.dart
lib/l10n/en.dart
lib/widgets/piano/piano_settings_button_group.dart

fix: TIO-106: rename instruments and display hold button

---

.github/workflows/reusable-upload-android-app.yaml
.github/workflows/reusable-upload-ios-app.yaml

chore: TIO-000: enable upload of apps after refactoring pipeline

---

android/app/build.gradle
android/fastlane/Appfile
android/fastlane/Fastfile
ios/fastlane/Appfile
ios/fastlane/Fastfile
ios/fastlane/Matchfile

chore: TIO-000: use app id consistently for fastlane

---

lib/l10n/de.dart
lib/l10n/en.dart
lib/widgets/parent_tool/parent_island_view.dart

fix: TIO-117: improve linking of tools

---

lib/pages/media_player/media_player.dart

style: TIO-109: improve position of tutorial pointers

---

lib/l10n/app_localization.dart
lib/l10n/de.dart
lib/l10n/en.dart
lib/pages/media_player/media_player.dart
lib/pages/media_player/media_player_loop_button.dart
rust/Cargo.lock
rust/Cargo.toml

Loop nothing:
Loop one:
Loop all:

refactor: TIO-109: show one toggle button with three loop states

---

.github/workflows/reusable-verify.yaml
lib/domain/metronome/metronome.dart
lib/domain/metronome/metronome_beat_event_utils.dart
test/domain/metronome/metronome_beat_event_test.dart
test/domain/metronome/metronome_primary_current_beat_test.dart
test/domain/metronome/metronome_secondary_current_beat_test.dart

fix: TIO-152: do not blink on mute beat

---

.github/workflows/reusable-build-ios-app.yaml
.github/workflows/reusable-upload-ios-app.yaml

fix: TIO-179: use new macOS 14 version in pipelines

---

ios/Podfile.lock
lib/pages/media_player/media_player.dart
lib/pages/metronome/advanced_rhythm_group_editor.dart
lib/pages/metronome/metronome.dart
lib/pages/parent_tool/parent_tool.dart
lib/pages/piano/piano.dart
lib/pages/project_page/project_page.dart
lib/pages/projects_page/projects_page.dart
lib/pages/tuner/tuner.dart
lib/util/tutorial_util.dart
pubspec.lock
pubspec.yaml
test/integration/tutorials/tutorials_test.dart
widgetbook/ios/Podfile.lock
widgetbook/pubspec.lock

The update of the tutorial dependency reveals some techn. debt and issues:
- tutorials in tools are now disposed correctly (important for handling pending timers)
- tutorial tests are improved

chore: TIO-84: update minor and bugfix versions

---

lib/l10n/de.dart
lib/pages/parent_tool/parent_tool.dart

chore: TIO-179: implement feedback

---

.github/workflows/reusable-build-android-app.yaml

build: TIO-311: TIO-312: increase android ndk-version for android build pipeline

---

android/app/build.gradle

build: TIO-311: update target and and compiled android sdk version

---

.github/dependabot.yaml

chore: TIO-323: Setup Dependabot support for Rust dependencies

---

lib/l10n/de.dart
lib/l10n/en.dart

refactor: TIO-179: piano hold function tutorial

---

lib/widgets/parent_tool/parent_island_view.dart
test/integration/metronome/tool_connections_test.dart
test/integration/piano/tool_connections_test.dart
test/integration/tuner/tool_connections_test.dart

fix: TIO-264: deactivate MP island tool support in MP until feature completion

---

lib/pages/media_player/media_player.dart

fix: TIO-179: fix tutorial box position

---

lib/domain/metronome/metronome.dart
rust/src/api/modules/metronome.rs

fix: TIO-152: add 150ms visual delay on android; remove general beat delay
